In [13]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [14]:
modelo_logistico = LogisticRegression()

In [15]:
## Ejemplo sencillo 

## Dataset de prueba [Iris]

from sklearn import datasets
import pandas as pd
import numpy as np

iris = datasets.load_iris()
iris_df = pd.DataFrame(data= np.c_[iris['data'], iris['target'].astype(int)],
                        columns= iris['feature_names'] + ['target'])

iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [16]:
iris_df['target'].value_counts()

target
0.0    50
1.0    50
2.0    50
Name: count, dtype: int64

In [17]:
variables_entrada=['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
variable_salida='target'

X=iris_df[variables_entrada]
y=iris_df[variable_salida]


In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [20]:
modelo_logistico.coef_

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [21]:
## Entrenamos el modelo

modelo_logistico.fit(X_train, y_train)

LogisticRegression()

In [22]:
modelo_logistico.coef_

array([[-0.40538561,  0.86892188, -2.277875  , -0.95680118],
       [ 0.4664269 , -0.37487908, -0.18745251, -0.72127094],
       [-0.06104129, -0.4940428 ,  2.46532752,  1.67807213]])

In [23]:
modelo_logistico.predict(X_test)

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.])

In [38]:
modelo_logistico.predict_proba(X_test)

array([[4.09967959e-03, 8.12343753e-01, 1.83556567e-01],
       [9.41955381e-01, 5.80440391e-02, 5.80207952e-07],
       [1.58411063e-08, 2.09129900e-03, 9.97908685e-01],
       [6.82488977e-03, 7.73251372e-01, 2.19923739e-01],
       [1.59400225e-03, 7.51205931e-01, 2.47200067e-01],
       [9.50040956e-01, 4.99585850e-02, 4.58822382e-07],
       [7.78024646e-02, 9.04145055e-01, 1.80524805e-02],
       [1.79835495e-04, 1.47357851e-01, 8.52462314e-01],
       [2.42255562e-03, 7.80452749e-01, 2.17124695e-01],
       [2.89983004e-02, 9.40818591e-01, 3.01831083e-02],
       [4.73568680e-04, 2.25282293e-01, 7.74244139e-01],
       [9.62693742e-01, 3.73060740e-02, 1.84138915e-07],
       [9.69162386e-01, 3.08375177e-02, 9.66516280e-08],
       [9.56006791e-01, 4.39929433e-02, 2.65384135e-07],
       [9.76521687e-01, 2.34781232e-02, 1.89460116e-07],
       [4.76685588e-03, 6.63398477e-01, 3.31834667e-01],
       [9.67224423e-06, 2.67217983e-02, 9.73268529e-01],
       [2.76880578e-02, 9.45164

In [40]:
import joblib

joblib.dump(modelo_logistico, 'modelo_logistico.joblib')


['modelo_logistico.joblib']

In [28]:
np.array(y_test.to_list())

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.])

In [34]:
y_pred_inventado=[1., 0., 2., 2,2,2,2,1,1, 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0., 0., 0., 1., 0.,
       0., 2., 1., 0., 0., 0., 2., 1., 1., 0., 0.]

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

print(accuracy_score(y_test,y_pred_inventado))

0.8888888888888888


In [36]:
print(precision_score(y_test,y_pred_inventado,average='weighted'))

0.9015151515151516


In [37]:
print(confusion_matrix(y_test,y_pred_inventado))

[[18  0  1]
 [ 0 10  3]
 [ 0  1 12]]
